// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"time"
)

type Attempt struct {
	ID                  string
	DeliveryID          string
	Number              int32
	Status              string
	StatusCode          int32
	ErrorCode           string
	DurationMs          int64
	StartedAt           time.Time
	FinishedAt          *time.Time
	DestinationRevision *int64
}

type Delivery struct {
	ID             string
	EventID        string
	DestinationID  string
	ReplayOf       *string
	ReplayKey      *string
	Status         string
	AttemptCount   int32
	NextAttemptAt  *time.Time
	LastStatusCode int32
	LastError      string
	ClaimToken     *string
	LeaseUntil     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Destination struct {
	ID           string
	Name         string
	Url          string
	SecretCipher []byte
	Enabled      bool
	Archived     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Revision     int64
}

type Event struct {
	ID             string
	DestinationID  string
	EventType      string
	IdempotencyKey *string
	Payload        []byte
	PayloadBytes   int32
	PayloadSha256  string
	CreatedAt      time.Time
}
