// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package storedb

import (
	"context"
	"time"
)

const deliveryAttempts = `-- name: DeliveryAttempts :many
SELECT id,number,status,status_code,error_code,duration_ms,started_at,finished_at,destination_revision FROM attempts WHERE delivery_id=$1 ORDER BY number
`

type DeliveryAttemptsRow struct {
	ID                  string
	Number              int32
	Status              string
	StatusCode          int32
	ErrorCode           string
	DurationMs          int64
	StartedAt           time.Time
	FinishedAt          *time.Time
	DestinationRevision *int64
}

func (q *Queries) DeliveryAttempts(ctx context.Context, deliveryID string) ([]DeliveryAttemptsRow, error) {
	rows, err := q.db.Query(ctx, deliveryAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttemptsRow{}
	for rows.Next() {
		var i DeliveryAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.StatusCode,
			&i.ErrorCode,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DestinationRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventDeliveries = `-- name: EventDeliveries :many
SELECT id,event_id,destination_id,COALESCE(replay_of,'')::text AS replay_of,status,attempt_count,next_attempt_at,last_status_code,last_error,created_at,updated_at FROM deliveries WHERE event_id=$1 ORDER BY id DESC LIMIT 100
`

type EventDeliveriesRow struct {
	ID             string
	EventID        string
	DestinationID  string
	ReplayOf       string
	Status         string
	AttemptCount   int32
	NextAttemptAt  *time.Time
	LastStatusCode int32
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) EventDeliveries(ctx context.Context, eventID string) ([]EventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, eventDeliveries, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDeliveriesRow{}
	for rows.Next() {
		var i EventDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DestinationID,
			&i.ReplayOf,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDelivery = `-- name: GetDelivery :one
SELECT id,event_id,destination_id,COALESCE(replay_of,'')::text AS replay_of,status,attempt_count,next_attempt_at,last_status_code,last_error,created_at,updated_at FROM deliveries WHERE id=$1
`

type GetDeliveryRow struct {
	ID             string
	EventID        string
	DestinationID  string
	ReplayOf       string
	Status         string
	AttemptCount   int32
	NextAttemptAt  *time.Time
	LastStatusCode int32
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetDelivery(ctx context.Context, id string) (GetDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i GetDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DestinationID,
		&i.ReplayOf,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDestination = `-- name: GetDestination :one
SELECT id,name,url,enabled,archived,created_at,updated_at,revision FROM destinations WHERE id=$1
`

type GetDestinationRow struct {
	ID        string
	Name      string
	Url       string
	Enabled   bool
	Archived  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	Revision  int64
}

func (q *Queries) GetDestination(ctx context.Context, id string) (GetDestinationRow, error) {
	row := q.db.QueryRow(ctx, getDestination, id)
	var i GetDestinationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id,destination_id,event_type,payload_bytes,payload_sha256,(payload IS NULL)::boolean AS redacted,created_at FROM events WHERE id=$1
`

type GetEventRow struct {
	ID            string
	DestinationID string
	EventType     string
	PayloadBytes  int32
	PayloadSha256 string
	Redacted      bool
	CreatedAt     time.Time
}

func (q *Queries) GetEvent(ctx context.Context, id string) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.EventType,
		&i.PayloadBytes,
		&i.PayloadSha256,
		&i.Redacted,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id,event_id,destination_id,COALESCE(replay_of,'')::text AS replay_of,status,attempt_count,next_attempt_at,last_status_code,last_error,created_at,updated_at FROM deliveries
WHERE ($1::text = '' OR id < $1)
AND ($2::text = '' OR destination_id=$2)
AND ($3::text = '' OR event_id=$3)
AND ($4::text = '' OR status=$4 OR ($4='active' AND status IN ('pending','retrying','delivering')))
ORDER BY id DESC LIMIT $5
`

type ListDeliveriesParams struct {
	BeforeID      string
	DestinationID string
	EventID       string
	Status        string
	PageLimit     int32
}

type ListDeliveriesRow struct {
	ID             string
	EventID        string
	DestinationID  string
	ReplayOf       string
	Status         string
	AttemptCount   int32
	NextAttemptAt  *time.Time
	LastStatusCode int32
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]ListDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.BeforeID,
		arg.DestinationID,
		arg.EventID,
		arg.Status,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesRow{}
	for rows.Next() {
		var i ListDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DestinationID,
			&i.ReplayOf,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinations = `-- name: ListDestinations :many
SELECT id,name,url,enabled,archived,created_at,updated_at,revision FROM destinations WHERE ($1::text = '' OR id < $1) ORDER BY id DESC LIMIT $2
`

type ListDestinationsParams struct {
	BeforeID  string
	PageLimit int32
}

type ListDestinationsRow struct {
	ID        string
	Name      string
	Url       string
	Enabled   bool
	Archived  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	Revision  int64
}

func (q *Queries) ListDestinations(ctx context.Context, arg ListDestinationsParams) ([]ListDestinationsRow, error) {
	rows, err := q.db.Query(ctx, listDestinations, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDestinationsRow{}
	for rows.Next() {
		var i ListDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id,destination_id,event_type,payload_bytes,payload_sha256,(payload IS NULL)::boolean AS redacted,created_at FROM events
WHERE ($1::text = '' OR id < $1)
AND ($2::text = '' OR destination_id=$2)
AND ($3::text = '' OR event_type=$3)
ORDER BY id DESC LIMIT $4
`

type ListEventsParams struct {
	BeforeID      string
	DestinationID string
	EventType     string
	PageLimit     int32
}

type ListEventsRow struct {
	ID            string
	DestinationID string
	EventType     string
	PayloadBytes  int32
	PayloadSha256 string
	Redacted      bool
	CreatedAt     time.Time
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.BeforeID,
		arg.DestinationID,
		arg.EventType,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.EventType,
			&i.PayloadBytes,
			&i.PayloadSha256,
			&i.Redacted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoveredDelivery = `-- name: RecoveredDelivery :one
WITH RECURSIVE lineage AS (
 SELECT source.id,source.status FROM deliveries source WHERE source.replay_of=$1
 UNION ALL
 SELECT d.id,d.status FROM deliveries d JOIN lineage l ON d.replay_of=l.id
)
SELECT id FROM lineage WHERE status='succeeded' ORDER BY id DESC LIMIT 1
`

func (q *Queries) RecoveredDelivery(ctx context.Context, replayOf *string) (string, error) {
	row := q.db.QueryRow(ctx, recoveredDelivery, replayOf)
	var id string
	err := row.Scan(&id)
	return id, err
}

const recoveredEvent = `-- name: RecoveredEvent :one
WITH RECURSIVE lineage AS (
 SELECT source.id,source.status FROM deliveries source WHERE source.event_id=$1 AND source.status='dead'
 UNION
 SELECT d.id,d.status FROM deliveries d JOIN lineage l ON d.replay_of=l.id
)
SELECT id FROM lineage WHERE status='succeeded' ORDER BY id DESC LIMIT 1
`

func (q *Queries) RecoveredEvent(ctx context.Context, eventID string) (string, error) {
	row := q.db.QueryRow(ctx, recoveredEvent, eventID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const stats = `-- name: Stats :one
WITH work AS (
 SELECT d.id, d.event_id, d.destination_id, d.replay_of, d.replay_key, d.status, d.attempt_count, d.next_attempt_at, d.last_status_code, d.last_error, d.claim_token, d.lease_until, d.created_at, d.updated_at, t.enabled, t.archived, e.payload IS NOT NULL AS payload_available
 FROM deliveries d JOIN destinations t ON t.id=d.destination_id JOIN events e ON e.id=d.event_id
), queued AS (
 SELECT id, event_id, destination_id, replay_of, replay_key, status, attempt_count, next_attempt_at, last_status_code, last_error, claim_token, lease_until, created_at, updated_at, enabled, archived, payload_available, NOT archived AND payload_available AND attempt_count < $1::integer AS claimable
 FROM work WHERE status IN ('pending','retrying')
)
SELECT
 (SELECT count(*) FROM destinations WHERE NOT archived) AS destinations,
 (SELECT count(*) FROM events) AS events,
 count(*) FILTER (WHERE status='pending') AS pending,
 count(*) FILTER (WHERE status='retrying') AS retrying,
 count(*) FILTER (WHERE status='delivering') AS delivering,
 count(*) FILTER (WHERE status='succeeded') AS succeeded,
 count(*) FILTER (WHERE status='dead') AS dead,
 count(*) FILTER (WHERE status='canceled') AS canceled,
 (SELECT count(*) FROM queued WHERE claimable AND NOT enabled) AS paused,
 (SELECT count(*) FROM queued WHERE claimable AND enabled AND next_attempt_at<=now()) AS eligible,
 (SELECT count(*) FROM queued WHERE claimable AND enabled AND next_attempt_at>now()) AS scheduled,
 (SELECT COALESCE(max(EXTRACT(EPOCH FROM now()-next_attempt_at)),0)::double precision FROM queued WHERE claimable AND enabled AND next_attempt_at<=now()) AS oldest_eligible_queued_age_seconds
FROM work
`

type StatsRow struct {
	Destinations                   int64
	Events                         int64
	Pending                        int64
	Retrying                       int64
	Delivering                     int64
	Succeeded                      int64
	Dead                           int64
	Canceled                       int64
	Paused                         int64
	Eligible                       int64
	Scheduled                      int64
	OldestEligibleQueuedAgeSeconds float64
}

func (q *Queries) Stats(ctx context.Context, maxAttempts int32) (StatsRow, error) {
	row := q.db.QueryRow(ctx, stats, maxAttempts)
	var i StatsRow
	err := row.Scan(
		&i.Destinations,
		&i.Events,
		&i.Pending,
		&i.Retrying,
		&i.Delivering,
		&i.Succeeded,
		&i.Dead,
		&i.Canceled,
		&i.Paused,
		&i.Eligible,
		&i.Scheduled,
		&i.OldestEligibleQueuedAgeSeconds,
	)
	return i, err
}
